name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/Randdalf/fplcache.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main || echo "No changes to merge"

      - name: Push to your fork
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
